
<div class="wrapper">
    <div class="middle">
    <form method="POST" action="admin/usuario/save">  

    <br>
    <h4> Usuário </h4>
        
    <div class="form-group">
            <label>Nome:</label>
            <input type="text" name="nome" class="form-control" value="<?php echo $view_dados->nome;?>" required>
    </div>

    <div class="form-group">
            <label>Usuario:</label>
            <input type="text" name="usuario" class="form-control" value="<?php echo $view_dados->usuario;?>" required>
    </div>


    <div class="form-group">
            <label>Senha:</label>
            <input type="password" name="senha" class="form-control" maxlength="32" value="<?php echo $view_dados->senha;?>" required>
    </div>

    <input type="hidden" name="st_ativo" class="form-control" maxlength="32" value="1" required>


    <p><button type="submit" class="btn btn-sm btn-primary">Gravar</button></p>

    </form>
    </div>
</div>