<div class="wrapper">
    <div class="middle">
    <form method="POST" action="admin/sessao/validar">
        <h5><p align="center">Área Restrita</p></h5>


        <div class="form-group">
            <label>Usuário</label>
            <input type="text" name="usuario" class="form-control">
        </div>

        <div class="form-group">
            <label>Senha</label>
            <input type="password" name="senha" class="form-control">
        </div>

        <p><button type="submit" name="logar" class="btn btn-sm btn-primary">LOGAR</button></p>
        
    </form>
    </div>
</div>