<!DOCTYPE html>
<html lang="pt-br">
<head>
    <base href="<?php echo APP_ROOT; ?>"/admin>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title> Acesso Restrito - Meu Painel </title>
    <link href="content\assets\css\bootstrap.min.css" type="text/css" rel="stylesheet">
    <link href="content\admin\css\style.login.css" type="text/css" rel="stylesheet">
</head>
<body>
    <?php $this->Render(); ?>
    <script src="content\assets\jquery-3.3.1.min.js"></script>
    <script src="content\assets\js\bootstrap.min.js"></script>
</body>
</html>